n = int(input())
list0 = list(map(int, input().split()))
list1 = list(map(int, input().split()))
list2 = list(map(int, input().split()))
a0 = sum(list0)
a1 = sum(list1)
a2 = sum(list2)
print(a0 - a1)
print(a1 - a2)
