N = int(input())
L1 = list(map(int,input().split()))
L2 = list(map(int,input().split()))
L3 = list(map(int,input().split()))
EzZ=sum(L1)
EzZz=sum(L2)
EzZzZ=sum(L3)
print(EzZ - EzZz)
print(EzZz - EzZzZ)
