m = int(input())
a = list(map(int,input().split()))
b = list(map(int,input().split()))
c = list(map(int,input().split()))
a = sorted(a)
b = sorted(b)
c = sorted(c)
s = sum(a)
s1 = sum(b)
s2 = sum(c)
print(s-s1)
print(s1-s2)