l = int(input())
n1 = list(map(int,input().split()))
n2 = list(map(int,input().split()))
n3 = list(map(int,input().split()))
sumline1 = sum(n1)
sumline2 = sum(n2)
sumline3 = sum(n3)
error1 = (sumline1-sumline2)
error2 = (sumline2-sumline3)
print(error1)
print(error2)
