# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OKbrG27mOdvGhdgzvRm1BawZ7TdpQYBR
"""

t=int(input())
while t>0:
  n=int(input())
  k=0
  list1=list(map(int,input().split(" ")))
  e=list1[0]+list1[1]
  for a in range(2,n):
    if e<=list1[a]:
      print(""+str(1)+" "+str(2)+" "+str(a+1))
      k=-1
      break
  if k!=-1:   
    print("-1")

  
  
  
  
  
  
  
  
  
  
  
  
  
  t=t-1