# -*- coding: utf-8 -*-
"""Untitled109.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X8-VINDMTMre7Qt2DyQiUJHJz7Qf9Y8v
"""

for _ in range(int(input())):
  n=int(input())
  l=[int(x) for x in input().split()]
  if l[0]+l[1]<=l[-1]:
    print(1,2,len(l))
  else:
    print(-1)

