n = int(input())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
c = list(map(int, input().split()))
sum_a = sum(a)
sum_b = sum(b)
sum_c = sum(c)
print(sum_a - sum_b)
print(sum_b - sum_c)
