n=int(input())
firs_er= input().split()
firs_er=list(map(int, firs_er))
second_er= input().split()
second_er=list(map(int, second_er))
fr_er= map(int,input().split())
fr_er=list(map(int, fr_er))
print(sum(firs_er)-sum(second_er))
print(sum(second_er)-sum(fr_er))
