n = int(input())
arr = list(map(int, input().split()))
s1 = sum(arr)
brr = list(map(int, input().split()))
s2 = sum(brr)
crr = list(map(int, input().split()))
s3 = sum(crr)
print(s1 - s2)
print(s2 - s3)
