n = int(input())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
c = list(map(int, input().split()))
sumA = sum(a)
sumB = sum(b)
sumC = sum(c)
print(sumA - sumB)
print(sumB - sumC)