for w in range(int(input())):
    n=int(input())
    l=[]
    for i in range(n):
        l.append(list(str(input())))
    #print(l)
    if(l[0][1]==l[1][0]):
        if(l[n-1][n-2]==l[n-2][n-1]):
            if(l[n-1][n-2]==l[0][1]):
                print(2)
                print(n,n-1)
                print(n-1,n)
            else:
                print(0)
        else:
            print(1)
            if(l[n-1][n-2]==l[0][1]):
                print(n,n-1)
            else:
                print(n-1,n)
    else:
        if(l[n-1][n-2]==l[n-2][n-1]):
            print(1)
            if(l[0][1]==l[n-1][n-2]):
                print(1,2)
            else:
                print(2,1)
        else:
            print(2)
            if(l[0][1]!='0'):
                print(1,2)
            if(l[1][0]!='0'):
                print(2,1)
            if(l[n-1][n-2]!='1'):
                print(n,n-1)
            if(l[n-2][n-1]!='1'):
                print(n-1,n)